### PR TITLE
[FEAT] standard figure style

### PR DESCRIPTION
**Pull request by MOchiara**

### CODE REVIEW

**Comment by MOchiara** [comment]
I tried and add os and warnings to requirements but I get errors in the test

**Comment by MOchiara** [comment]
Fair fair!

**Comment by callumrollo** [comment]
The use of context managers and style is nice! But I don't like using os.chdir for this. The end user might depend on staying in the directory of the script they are writing! Try this instead:

```python
dir = os.path.dirname(os.path.realpath(__file__))
glidertest_style_file = f"{dir}/glidertest.mplstyle"

with plt.style.context(glidertest_style_file):
    plt.etc.
```

**Comment by callumrollo** [comment]
This will also make it more flexible in future if e.g. we let the user pass their own style file to functions (don't add this now though!)

**Comment by MOchiara** [comment]
Very true!
I will fix it

**Review by callumrollo — APPROVED** [review]

**Pull request merged**
