### PR TITLE
Updated tools - split some functions and also updated demo

### PR DESCRIPTION
**Pull request by MOchiara**

### CODE REVIEW

**Comment by MOchiara** [comment]
Ok I think I will change the tests because I have changes some of the functions name and input so they fail

**Comment by callumrollo** [comment]
change the tests in this branch so that they call the new function name

**Comment by MOchiara** [comment]
Wohoooooo my slow brain managed to figure it out hahahha very slow brain today haha
@callumrollo all yours now

**Comment by callumrollo** [comment]
Looks good. In future I recommend running tests locally before you commit, so you don't need to do patch commits because of a bad indent etc.

**Pull request merged**
