### PR TITLE
[FIX] Adjusted T/S plot with histograms on the two sides

### PR DESCRIPTION
**Pull request by MOchiara**
Eleanor wanted the T/S to look like this with the histograms on the two axis 
image

### CODE REVIEW

**Comment by MOchiara** [comment]
@eleanorfrajka

**Comment by eleanorfrajka** [comment]
Looks good!

**Comment by eleanorfrajka** [comment]
We could demonstrate the figure resize in the notebook on this one, and resize to, maybe 10 inches wide and 10 tall, so that the axes look more square after?  (see Callum's comment in PR #129 )

**Comment by MOchiara** [comment]
Sure! This is a good idea! 
I am about to put a new PR for the profile duration and I am modifiying the demo there so I can add that line to the PR

**Review by callumrollo — APPROVED** [review]
lgtm! Let's merge this before other PRs come in

**Pull request merged**
