### PR TITLE
[FEAT] set default dates for all functions

### PR DESCRIPTION
**Pull request by callumrollo**
This sets hopefully sensible default dates and date ranges for all functions that need them

### CODE REVIEW

**Comment by callumrollo** [comment]
I also updated the notebook to use the default dataset for PAR

**Comment by eleanorfrajka** [comment]
I like this.  There are also some functions which have a start_prof and end_prof.
- Low priority to consider: Possible to allow the user to either provide a start and end PROFILE_NUMBER or a start and end time?
- Remark: The date format you're using is YYYY-MM-DD, which is my preferred.  But OG1 uses YYYYmmddTHHMMss.  This would mean that if the user wants to pick the first week of the mission, and work with the start_date or something from the file attributes, they'll have to do some re-formatting.  Though personally, I find the OG1 date format really hard to read.

As I'm writing this, I'm thinking the bullets are possibly "issues" that could be implemented or discussed and then closed.

**Review by MOchiara — APPROVED** [review]
Looks great!

**Comment by callumrollo** [comment]
Looks good! In future this should probably be a separate PR though. It can get a little tricky to compare the diffs when we add more functionality to a PR

Once we've merged in #59 I'll merge this :)

**Comment by MOchiara** [comment]
Ok ok! Sorry! I saw the issue was tagged here so though of doing all here

**Pull request merged**
