### PR TITLE
Add checker for profile index consistency

### PR DESCRIPTION
**Pull request by MOchiara**

### CODE REVIEW

**Comment by MOchiara** [comment]
We were looking at Emelie's dataset and we saw issues in how the profile index was assigned: lost of 0s in the middle of the dataset and other issues. This is to check for that and highlight to the users possible issues. This is easily solved by tuning in some parameters in the pyglider fuction used to assing the profile

**Comment by callumrollo** [comment]
This function is a good addition! I have a few suggestions:

Are you using an editor like Pycharm or VS code for this? It should catch easy errors like:
-  typos (wheather etc.)
- pythonic improvements like using `if not pd.Series(ds).is_monotonic_increasing` rather than `if pd.Series(ds).is_monotonic_increasing == False`
- having the docstring at the top of the function ` plot_profIncrease`

It's good to use a code editor to catch/autocorrect these

Also, we usually use `ds` to refer to an xarray DataSet, not a DataArray as is used in `check_monotony`. The docstring does specify that `ds` must be a DataArray, which is good! But maybe call it `da` or something else instead?

**Comment by MOchiara** [comment]
@callumrollo yeah I normally use pycharm but I have to do a mea culpa and admit I was lazy and did not use it haha
Should look better now?

**Review by callumrollo — APPROVED** [review]
to err is human my friend

**Pull request merged**
