### PR TITLE
Prepare for tests

### PR DESCRIPTION
**Pull request by MOchiara**

### CODE REVIEW

**Comment by MOchiara** [comment]
Ok I feel like I made a but of a mess before and now I cant undo it @callumrollo

**Comment by callumrollo** [comment]
Looks fine! Now you just need to add some tests. Try to get them to run locally before committing, then we can work on stuff like github actions to run them automatically

**Comment by MOchiara** [comment]
@callumrollo ok I should have added all. I used the same functions you suggested, worked fine when I tested it locally

**Comment by MOchiara** [comment]
Should we do the workflow separately?

**Comment by callumrollo** [comment]
nah add that in too, get it all done in one :)

**Comment by MOchiara** [comment]
@callumrollo windows and mac tests are super slow, do we want to keep them anyways?

**Comment by callumrollo** [comment]
It's good to test against a wide range of systems. We should ideally get to the bottom of this. I'll see if they also are slow on  #16 otherwise we can remove the windows and mac tests for now

**Comment by MOchiara** [comment]
Sounds good! Let's see how it runs on the other one

**Comment by MOchiara** [comment]
Why is mine so slow?

**Comment by MOchiara** [comment]
Wohooooo!

**Pull request merged**
